### ISSUE TITLE
Webpage book preview

### ISSUE THREAD

**Issue by noah-curran** [IzzySoft/miniCalOPe#5]
I'm not sure if this project is still maintained, but I think it would be a good feature to allow users to preview a book before they download it. This could be helpful in cases where they don't have the hard drive space or desire to download it locally. There might also be issues with opening files due to there not being any native software. Just some thoughts.

**Comment by IzzySoft** [comment]
Thanks @noah-curran! There are browser addons which can be used to read EPUBs in the web browser. Would that fit? I doubt I find the time to implement EPUB preview in a useful way anytime soon.

**Comment by noah-curran** [comment]
@IzzySoft I think that should actually be sufficient. Thanks.
